-- Create shifts table
create table public.shifts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  clock_in timestamptz not null,
  clock_out timestamptz,
  status text not null,
  notes text
);

-- Enable RLS for shifts
alter table public.shifts enable row level security;

create policy "Users can view their own shifts"
  on shifts for select
  using (auth.uid() = user_id);

create policy "Users can insert their own shifts"
  on shifts for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own shifts"
  on shifts for update
  using (auth.uid() = user_id);

create policy "Users can delete their own shifts"
  on shifts for delete
  using (auth.uid() = user_id);


-- Create breaks table
create table public.breaks (
  id bigint generated by default as identity primary key,
  shift_id bigint references public.shifts on delete cascade not null,
  user_id uuid references auth.users not null,
  start_time timestamptz not null,
  end_time timestamptz
);

-- Enable RLS for breaks
alter table public.breaks enable row level security;

create policy "Users can view their own breaks"
  on breaks for select
  using (auth.uid() = user_id);

create policy "Users can insert their own breaks"
  on breaks for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own breaks"
  on breaks for update
  using (auth.uid() = user_id);

create policy "Users can delete their own breaks"
  on breaks for delete
  using (auth.uid() = user_id);
